site_name: pinax-announcements
pages:
- [index.md, Home]
- [usage.md, Usage]
- [templates.md, Templates]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-announcements
site_description: "documentation for pinax-announcements, an announcements app for Django sites"
site_author: "Pinax Team"
markdown_extensions: [admonition]
